import { API_BASE, API_VER } from "@/config/config";

export default {
  USERS: `${API_BASE}/${API_VER}/users`,
  USER: `${API_BASE}/${API_VER}/users/:userId`,
  REGISTER: `${API_BASE}/${API_VER}/auth/register`,

  FARMS: `${API_BASE}/${API_VER}/farms`,
  FARM: `${API_BASE}/${API_VER}/farms/:farmId`,
  FARM_WEATHER: `${API_BASE}/${API_VER}/farms/:farmId/weather`,

  RESERVOIRS: `${API_BASE}/${API_VER}/farms/:farmId/reservoirs`,
  RESERVOIR: `${API_BASE}/${API_VER}/farms/:farmId/reservoirs/:reservoirId`,

  POLYHOUSES: `${API_BASE}/${API_VER}/farms/:farmId/polyhouses`,
  POLYHOUSE_SENSOR_DATA: `${API_BASE}/${API_VER}/sensors?polyhouseId=:polyhouseId&isGraph=true`,
  POLYHOUSE_COMPONENT_DATA: `${API_BASE}/${API_VER}/sensors?polyhouseId=:polyhouseId&isGraph=false`,
  NURSERY_SENSOR_DATA: `${API_BASE}/${API_VER}/sensors?nurseryId=:nurseryId&isGraph=true`,
  NURSERY_COMPONENT_DATA: `${API_BASE}/${API_VER}/sensors?nurseryId=:nurseryId&isGraph=false`,
  ZONE_SENSOR_DATA: `${API_BASE}/${API_VER}/sensors?zoneId=:zoneId&isGraph=true`,
  ZONE_COMPONENT_DATA: `${API_BASE}/${API_VER}/sensors?zoneId=:zoneId&isGraph=false`,
  SENSOR_UPDATE: `${API_BASE}/${API_VER}/sensors/:sensorId/parameters/:parameterId`,
  SENSOR_SCHEDULE: `${API_BASE}/${API_VER}/sensors/:sensorId/parameters/:parameterId/schedule/:scheduleId`,
  LIFE_CYCLE: `${API_BASE}/${API_VER}/workflow/:polyhouseId/instances`,
  DELETE_LIFE_CYCLE: `${API_BASE}/${API_VER}/workflow/instances/:workflowInstancesId`,
  START_LIFECYCLE: `${API_BASE}/${API_VER}/workflow/:polyhouseId/instances/:workflowInstancesId/start`,
  LIFECYCLE_COMPLETED: `${API_BASE}/${API_VER}/workflow/:polyhouseId/instances/:workflowInstancesId/COMPLETED`,
  MOVE_CROPS_LIFECYCLE: `${API_BASE}/${API_VER}/workflow/:polyhouseId/instances/:workflowInstancesId/move/:stepId`,
  HARVEST_CROPS_LIFECYCLE: `${API_BASE}/${API_VER}/workflow/:polyhouseId/instances/:workflowInstancesId/batches/:stepId`,
  POLYHOUSE: `${API_BASE}/${API_VER}/farms/:farmId/polyhouses/:polyhouseId`,
  NURSERY: `${API_BASE}/${API_VER}/farms/:farmId/polyhouses/:polyhouseId/nurseries/:nurseryId`,
  NURSERIES: `${API_BASE}/${API_VER}/farms/:farmId/polyhouses/:polyhouseId/nurseries`,
  ZONES: `${API_BASE}/${API_VER}/farms/:farmId/polyhouses/:polyhouseId/zones`,
  ZONE: `${API_BASE}/${API_VER}/farms/:farmId/polyhouses/:polyhouseId/zones/:zoneId`,
  SENSOR_DATA: `${API_BASE}/${API_VER}/sensor-data/farms/:farmId/devices/:deviceId/sensors/:sensorId`,
  SENSORS : `${API_BASE}/${API_VER}/sensors`,
  SENSOR : `${API_BASE}/${API_VER}/sensors/:sensorId`,

  SENSOR_GRAPH_DATA: `${API_BASE}/${API_VER}/analytics/sensor-data/:sensorId?duration=:duration`,
  BATCH: `${API_BASE}/${API_VER}/workflow/instances/batch/count/:polyhouseId`,

  ORGANIZATIONS: `${API_BASE}/${API_VER}/organisations`,
  INVENTORIES: `${API_BASE}/${API_VER}/inventories`,
  INVENTORY: `${API_BASE}/${API_VER}/inventories/:inventoryId`,
  SUBCATEGORIES: `${API_BASE}/${API_VER}/products/sub-category`,
  PRODUCTS: `${API_BASE}/${API_VER}/products`,
  WORKFLOW: `${API_BASE}/${API_VER}/workflow`,
  WORKFLOW_INSTANCES: `${API_BASE}/${API_VER}/workflow/instances`,
  POLYHOUSE_WORKFLOW_INSTANCES: `${API_BASE}/${API_VER}/workflow/:polyhouseId/instances/:workflowInstancesId`,
  UPDATE_WORKFLOW: `${API_BASE}/${API_VER}/workflow/:workflowId`,
  TASKS: `${API_BASE}/${API_VER}/tasks`,
  TASK: `${API_BASE}/${API_VER}/tasks/:taskId`,

  HARVESTED_BREAKUP: `${API_BASE}/${API_VER}/analytics?farmId=:farmId&&type=life_cycle_wise_harvest`,
  FARM_UTILIZATION_ON_CROPS: `${API_BASE}/${API_VER}/analytics/farm-utilization-based-on-crops/:farmId`,
  FARM_UTILIZATION_ON_STAGES: `${API_BASE}/${API_VER}/analytics/farm-utilization-based-on-stages/:farmId`,
  MORTALITY_RATE: `${API_BASE}/${API_VER}/analytics?farmId=:farmId&&type=mortality_ratio`,
  DASHBOARD_TASKS: `${API_BASE}/${API_VER}/analytics?farmId=:farmId&&type=task`,
  BATCH_HARVESTED: `${API_BASE}/${API_VER}/analytics?farmId=:farmId&&type=batch_wise_harvest`,
  FARM_METRICS: `${API_BASE}/${API_VER}/farms/:farmId/metrics`,
};
