const routePaths = {
  login: "/login",
  userManagement: "/users",
  signUp: "/signUp",
  forgotPassword: "/forgot-password",
  userVerfication: "/user-verfication",
  farm: "/farm",
  polyhouse: "/polyhouse",
  reservoirs: "/reservoirs",
  polyhouseCreate: "/polyhouse/create",
  polyhouseDetails: "/polyhouse/:polyhouseId",
  nurseries: "/polyhouse/:polyhouseId/nurseries",
  nurseryDetails: "/polyhouse/:polyhouseId/nursery/:nurseryId",
  zones: "/polyhouse/:polyhouseId/zones",
  zoneDetails: "/polyhouse/:polyhouseId/zone/:zoneId",
  polyhouseSensorDetails: "/polyhouse/:polyhouseId/:sensorName",
  zoneSensorDetails: "/polyhouse/:polyhouseId/zone/:zoneId/:sensorName",
  nurserySensorDetails:
    "/polyhouse/:polyhouseId/nursery/:nurseryId/:sensorName",
  lifeCycle: "/polyhouse/:polyhouseId/life_cycles",
  addLifeCycle: "/polyhouse/:polyhouseId/life_cycles/add",
  updateLifeCycle: "/polyhouse/:polyhouseId/life_cycles/:lifeCycleId",
  startLifeCycle: "/polyhouse/:polyhouseId/life_cycles/:lifeCycleId/start",
  reservoirCreate: "/reservoir/create",
  inventory: "/inventory",
  addInventory: "/inventory/add",
  tasks: "/tasks",
  template: "/templates",
  templateCreate: "/templates/create",
  templateUpdate: "/templates/update/:workflowId",
  farmCreate: "/farm/create",
  organization: "/organization",
  profile: "/profile",
};

export default routePaths;
